Hitoko/config/routes.rb
Rails.application.routes.draw do

  resources :words, only: [:index, :new, :create, :edit, :update ,:destroy]do
    collection do
      post :confirm
    end
  end

 root 'top#index'
 

end

Hitoko/app/models/word.rb
class Word < ActiveRecord::Base
    validates :title, presence: true
    validates :content, presence: true,
                        length: {minimun: 1, maximum: 140}
end

Hitoko/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Hitoko/app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

Hitoko/app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_word, only: [:edit, :update, :destroy]
  def index
    @words = Word.all
  end

  def new
    if params[:back]
      @word = Word.new(words_params)
    else
      @word = Word.new
    end
  end

  def confirm
    @word = Word.new(words_params)
    render :new if @word.invalid?
  end
  
  def create
    @word = Word.new(words_params)
    if @word.save
     redirect_to words_path, notice: "ヒトコトを作成しました！"
    else
     render 'new'
    end
  end

  def edit
  end
  
  def update
    if @word.update(words_params)
      redirect_to words_path, notice: "ヒトコトを更新しました！"
    else
      render 'edit'
    end
  end
  
  def destroy
    @word.destroy
    redirect_to words_path, notice: "ヒトコトを削除しました！"
  end
  
  private
    def words_params
      params.require(:word).permit(:title, :content)
    end
    
    def set_word
      @word = Word.find(params[:id])
    end
    
end

Hitoko/app/helpers/application_helper.rb
module ApplicationHelper
end

Hitoko/app/helpers/top_helper.rb
module TopHelper
end

Hitoko/app/helpers/words_helper.rb
module WordsHelper
 def choose_new_or_edit
  if action_name == 'new' || action_name == 'confirm'
   confirm_words_path
  elsif action_name == 'edit'
   word_path
  end
 end
end

Hitoko/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hitoko</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <header>
    <ul>
      <li><%= link_to "Hitoko", root_path %></li>
      <li><%= link_to "トップページ", root_path %></li>
      <li><%= link_to "ヒトコト一覧", words_path %></li>
    </ul>
  </header>

<%= yield %>

  <footer>
    <p>運営会社DIVE INTO CODE株式会社</p>
    <p>© 2015-2016 Copyright DIVE INTO CODE Corp.</p>
  </footer>

</body>
</html>

Hitoko/app/views/top/index.html.erb
  <section class="main-header">
    <img src="<%= asset_path "hitoko.png" %>">
  </section>
  <section class="function container-fluid">
    <div class="row">
    <h2>Function</h2>
      <div class="function-images">
        <div class="col-md-6 col-sm-6">
          <div class="function-image">
            <img src="<%= asset_path "comment.png" %>">
            <p><%= link_to 'ヒトコト一覧', words_path %></p>
          </div>
        </div>
        <div class="col-md-6 col-sm-6">
          <div class="function-image">
            <img src="<%= asset_path "mails.png" %>">
            <p>お問い合わせ</p>
          </div>
        </div>
      </div>
    </div>
  </section>

Hitoko/app/views/words/_form.html.erb
<%= form_for(@word, url: choose_new_or_edit) do |f| %>
  <% if @word.errors.any? %>
    <div id="error_explanation">
      <h2><%= @word.errors.count %>件のエラーがあります。</h2>

      <ul>
      <% @word.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :タイトル %>
  <%= f.text_field :title, class: 'form-control' %>
  <br>
  <%= f.label :内容 %>
  <%= f.text_field :content, class: 'form-control' %>
  <br>
  <%= f.submit '投稿', class: 'btn btn-primary btn-block' %>
<% end %>

<%= link_to "ヒトコト一覧画面にもどる", words_path %>

Hitoko/app/views/words/confirm.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h3>以下の内容で、送信する。</h3>
    <%= form_for(@word) do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <p>タイトル:<%= @word.title %></p>
      <p>本文:<%= @word.content %></p>
      <%= f.submit "登録",class: 'btn btn-primary btn-block' %>
    <% end %>
    <%= form_for(@word, url: new_word_path, method: 'get') do |f| %>
      <%= f.hidden_field :title %>
      <%= f.hidden_field :content %>
      <%= f.submit "もどる", name: 'back', class: 'btn btn-default btn-block' %>
    <% end %>
  </div>
</div>

Hitoko/app/views/words/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ヒトコトを編集する</h2>
    <%= render 'form' %>
  </div>
</div>

Hitoko/app/views/words/index.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
    <p><%= notice %></p>
    <h1>ヒトコト一覧</h1>
      <%= link_to "ヒトコトを作成する", new_word_path, class: 'btn btn-default' %>
    <% @words.each do |word| %>
    <div class="row">
      <h4><strong><%= word.title %></strong></h4>
      <p><%= word.content %></p>
      <%= link_to "編集", edit_word_path(word.id), class: 'btn btn-default btn-sm btn-success' %>
      <%= link_to "削除", word_path(word.id), method: :delete, data: { confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm btn btn-danger' %>
    </div>
    <% end %>
  </div>
</div>

Hitoko/app/views/words/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
    <h2>ヒトコトを作成する</h2>
    <%= render 'form' %>
  </div>
</div>